### PR TITLE
Add WebEx, Mailing List, Meeting Notices and FINOS Antitrust Policy Slide to GitHub Agenda Template

### PR DESCRIPTION
**Pull request by mcleo-d**
## Description

This pull request adds the following items to the DevOps Mutualization meeting agenda template ...

- Webex details for meetings scheduled the 3rd Thursday of each month from Thursday 21st January 2021 @ 12pm ET / 5pm GMT onwards
- How to subscribe to the DevOps Mutualization mailing list
- FINOS meeting notices cc @aitana16 
- FINOS antitrust policy slide cc @aitana16

### FINOS Meeting Notices
```
## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
```

### FINOS Antitrust Policy Slide
```
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
```

### DevOps Mutualization Webex and Mailing List Details
```
### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=md62056638ba05fbea86b9582df94f807

### Dial-in
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 662 6070

**Github Repo:** https://github.com/finos/devops-mutualization/

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list
```

## Commits 
- add webex and mailing list details to meeting.md f3ed4d5
- add FINOS meeting notices 00c5089
- add FINOS policy slide to agenda f368f3e
- Merge branch 'master' into add-webex-details 2c2bc77

### CODE REVIEW

**Review by ashukla13 — APPROVED** [review]
LGTM

**Comment by jbjonesjr** [comment]
> Webex details

did we decide webex over zoom?

**Comment by mcleo-d** [comment]
> did we decide webex over zoom?

Hi @jbjonesjr - Zoom is definitely on the FINOS and LF roadmap, but the details of how project and SIG calls are scheduled and maintained are still being ironed out. We were actually talking this through as you raised this comment 😁 

Once Zoom's in place, I'll bring it to the SIG to discuss and agree before changing the details.

I hope this works?

James.

**Comment by mcleo-d** [comment]
> LGTM

PR merged on back of @ashukla13 approval.

**Comment by jbjonesjr** [comment]
@mcleo-d makes perfect sense!

**Pull request merged**
